### ISSUE TITLE
Multiple Acc Or Multi proxy? 

### ISSUE THREAD

**Issue by shaonturaj** [recitativonika/grass-network-bot#2]
Can you make this script to work for multiple accounts same time?  
Or 
Usuing multiple proxy using against one account will accumulate more points against one account? .You know better than me. Hope you will consider this

**Comment by recitativonika** [comment]
Maybe later, I don't have time to edit the script right now

**Comment by shaonturaj** [comment]
Awaiting for that.. But if possible make it Multiple proxy worker against one account. That would be great

**Comment by recitativonika** [comment]
pull the repo again

**Comment by shaonturaj** [comment]
So its One account against multiple proxy worker?  Or Single account per proxy?

**Comment by recitativonika** [comment]
account to all proxy list.
