### ISSUE TITLE
have an error

### ISSUE THREAD

**Issue by duonian12** [recitativonika/grass-network-bot#6]
Hi, yesterday I ran this script without any issues, but today, when I tried running it, this message appeared. Is this an error, or is it just how the tool is supposed to work?
![Screenshot 2024-12-04 124131](https://github.com/user-attachments/assets/45fc4bc4-2269-42e9-8ad3-c3caa7b0e04d)

**Comment by recitativonika** [comment]
your userID is wrong, it should look like this

`2oLV5yxxxxxxxxxx`

Try to get the UserID again, maybe you get it wrong?.
